### ISSUE TITLE
Error creating conda environment

### ISSUE THREAD

**Issue by Biomiha** [Alanocallaghan/snifter#10]
Hi,

I wonder if this has been reported before. I get a conda environment error when trying to run snifter::fitsne from RStudio.

    > TSNE_dims <- snifter::fitsne(x = iris[, -5])
    + '/Users/mihakosmac/Library/Caches/org.R-project.R/R/basilisk/1.8.1/0/bin/conda' 'create' '--yes' '--prefix' '/Users/mihakosmac/Library/Caches/org.R-project.R/R/basilisk/1.8.1/snifter/1.6.0/fitsne' 'python=3.7.7' '--quiet' '-c' 'conda-forge'
    Collecting package metadata (current_repodata.json): ...working... done
    Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): ...working... done
                                                                             
    Found conflicts! Looking for incompatible packages.
    This can take several minutes.  Press CTRL-C to abort.
    failed
    
    UnsatisfiableError: 
    Note that strict channel priority may have removed packages required for satisfiability.
    
    Error: Error creating conda environment '/Users/mihakosmac/Library/Caches/org.R-project.R/R/basilisk/1.8.1/snifter/1.6.0/fitsne' [exit code 1]

My session: 

    > sessionInfo()
    R version 4.2.2 (2022-10-31)
    Platform: x86_64-apple-darwin17.0 (64-bit)
    Running under: macOS Ventura 13.0.1
    
    Matrix products: default
    LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
    
    locale:
    [1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8
    
    attached base packages:
    [1] stats4    stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
     [1] snifter_1.6.0               reticulate_1.26             ggsci_2.9                   scMerge_1.12.0             
     [5] harmony_0.1.1               Rcpp_1.0.9                  scater_1.24.0               scran_1.24.1               
     [9] scuttle_1.6.3               SingleCellExperiment_1.18.1 SummarizedExperiment_1.26.1 Biobase_2.56.0             
    [13] GenomicRanges_1.48.0        GenomeInfoDb_1.32.4         IRanges_2.30.1              S4Vectors_0.34.0           
    [17] BiocGenerics_0.42.0         MatrixGenerics_1.8.1        matrixStats_0.63.0          forcats_0.5.2              
    [21] stringr_1.4.1               dplyr_1.0.10                purrr_0.3.5                 readr_2.1.3                
    [25] tidyr_1.2.1                 tibble_3.1.8                ggplot2_3.4.0               tidyverse_1.3.2   

Any help will be greatly appreciated.
Thanks.

**Comment by alanocallaghan** [comment]
Is this an arm64/apple silicon mac?

**Comment by alanocallaghan** [comment]
Ah, sorry just saw the architecture in the sessioninfo. Should work fine on x86 per the build reports: http://bioconductor.org/checkResults/release/bioc-LATEST/snifter/

Will investigate later

**Comment by Biomiha** [comment]
Apple M1 Macbook Pro

**Comment by alanocallaghan** [comment]
Oh, I thought based on the `x86_64` in the sessioninfo that it wasn't M1 silicon. I don't think the conda env can be satisfied on arm64 macs because opentsne isn't available on that platform: https://anaconda.org/conda-forge/opentsne

**Comment by Biomiha** [comment]
I can run openTSNE just fine in Terminal or even if I add a {python} code chunk to an RMarkdown notebook.

**Comment by alanocallaghan** [comment]
what happens if you try `conda create -n testing -c conda-forge opentsne` (or `mamba create`)

**Comment by Biomiha** [comment]
That creates the conda environment, however still no luck with the R implementation.

**Comment by alanocallaghan** [comment]
I am pretty sure M1 macs show up as `arm64-apple` rather than `x86_64-apple` in R.

Build report for arm64 is also fine http://bioconductor.org/checkResults/3.16/bioc-mac-arm64-LATEST/snifter/

**Comment by Biomiha** [comment]
Just to clarify I am running the intel version of R on an M1 macbook pro due to package compilation issues being reported with the M1 version of R.

**Comment by alanocallaghan** [comment]
I have no way to reproduce that environment, so unless you can get a more specific error out of conda I can be of little help

**Comment by Biomiha** [comment]
Okay, thanks for the help. It works using a python chunk in RStudio so that's a workable solution.

**Comment by alanocallaghan** [comment]
I've had an idea actually. Can you try running the following command?

```
/Users/mihakosmac/Library/Caches/org.R-project.R/R/basilisk/1.8.1/0/bin/conda create --yes --prefix /tmp/fitsne python=3.7.7 -c conda-forge
```

and if that fails, try this:
```
/Users/mihakosmac/Library/Caches/org.R-project.R/R/basilisk/1.8.1/0/bin/conda create --yes --prefix /tmp/fitsne python  -c conda-forge
```

if the second command succeeds, try this:

```
/Users/mihakosmac/Library/Caches/org.R-project.R/R/basilisk/1.8.1/0/bin/conda create --yes --prefix /tmp/fitsne opentsne  -c conda-forge
```
and if the third command succeeds can you report what versions of python and opentsne conda uses

**Comment by alanocallaghan** [comment]
(reporting any errors if they do fail)

**Comment by Biomiha** [comment]
Command 1 fails, 2 and 3 work.
conda lists the following: 
opentsne                  0.6.2            py39h6dc771e_1    conda-forge
python                    3.9.13          hf8d34f4_0_cpython    conda-forge

**Comment by alanocallaghan** [comment]
Can you post the error logs from command 1?

**Comment by Biomiha** [comment]
/Users/mihakosmac/Library/Caches/org.R-project.R/R/basilisk/1.8.1/0/bin/conda create --yes --prefix /tmp/fitsne python=3.7.7 -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: 
Note that strict channel priority may have removed packages required for satisfiability.

**Comment by alanocallaghan** [comment]
Just noticed you're running snifter 1.6. Please upgrade to 1.8 or higher (eg using `devtools::install_github("Alanocallaghan/snifter")`. I think that'll solve this problem.
