### ISSUE TITLE
What's with all the S3 stuff?

### ISSUE THREAD

**Issue by LTLA** [Alanocallaghan/snifter#3]
Do you really need `fi_tsne` to be a S3 method? Why not just call `as.matrix()` all the time? It's a no-op for matrices anyway.

The S3 methods around `openTSNE.tsne.TSNEEmbedding` are likely to be less relevant in light of #2. 

`embed` also conflicts with `stats::embed`, so you might consider giving it a more distinct name.

**Comment by alanocallaghan** [comment]
It's just an easy way to allow matrix/data.frame input while providing a semi-reasonable error for anything else

**Comment by LTLA** [comment]
Wouldn't it be more general to just allow anything that has an `as.matrix` method to be passed in? Then your function would work for `DataFrame`s and sparse matrices and whatever people want to feed in there.

**Comment by alanocallaghan** [comment]
Fair point
