### ISSUE TITLE
Windows being windows

### ISSUE THREAD

**Issue by alanocallaghan** [Alanocallaghan/snifter#5]
https://github.com/Alanocallaghan/snifter/actions/runs/174798063

PackagesNotFoundError: The following packages are not available from current channels:

  - scipy=1.5.1

**Comment by LTLA** [comment]
Might see what happens if you roll back to 1.5.0, https://anaconda.org/anaconda/scipy indicates that they don't have 1.5.1 anyway.

**Comment by alanocallaghan** [comment]
I rolled back to 1.5.0 and got [errors on mac](https://github.com/Alanocallaghan/snifter/runs/887231712?check_suite_focus=true), may have been unrelated tho

**Comment by alanocallaghan** [comment]
Plan atm is to wait until 1.5.1 rolls out. it's no skin off my nose if windows doesn't work and I'm not in a critical rush to submit to bioc

**Comment by LTLA** [comment]
One option is to use `basilisk.utils::isWindows()` and vary the argument in `BasiliskEnvironment` accordingly. An ugly hack for sure, but sometimes you gotta do what you gotta do.

**Comment by alanocallaghan** [comment]
I was thinking about trying that; may do and then revisit at some faraway later date if there's any notable inconsistencies. Also, bizarre - osx/linux are getting it from forge, that only has 1.3.2 on windows https://anaconda.org/conda-forge/scipy

**Comment by alanocallaghan** [comment]
Closed 30a4bae7b96
