### ISSUE TITLE
bioc build errors

### ISSUE THREAD

**Issue by alanocallaghan** [Alanocallaghan/snifter#6]
https://github.com/Bioconductor/Contributions/issues/1565
https://bioconductor.org/spb_reports/snifter_buildreport_20200721160231.html

**Comment by LTLA** [comment]
The Mac SPB seems to be broken ATM, see https://github.com/Bioconductor/Contributions/issues/1564#issuecomment-661966974. Don't know if this is also the cause for the conda failures but we'll just wait and see.

No idea what happened with the Windows failure though. At least it succeeds on the One True Operating System.

**Comment by alanocallaghan** [comment]
Ah thanks, I figured it wasn't my deal but hadn't gone looking yet. Honestly expected Windows to be a bit of a cluster, would be sort of disappointed if not at this point

**Comment by alanocallaghan** [comment]
linking this just so I get a link back and forth https://github.com/Bioconductor/Contributions/issues/1565
