### ISSUE TITLE
early_exaggeration_iter & early_exaggeration parameters

### ISSUE THREAD

**Issue by beng-phrasia** [Alanocallaghan/snifter#8]
Hi - Thank you for this package, it's extremely helpful! 

I have been running some analysis and digging through the fitsne parameters and it looks like the defaults for early_exaggeration_iter & early_exaggeration parameters have been switched around compared to the defaults used in the [openTSNE API](https://opentsne.readthedocs.io/en/latest/api/index.html) Is that correct? My analysis certainly got a lot clearer after switching them so just wanted to raise in case it would help anyone else. 

Sorry if I've missed something and thank you again for such a useful package.

**Comment by alanocallaghan** [comment]
Thanks for the heads up, just an error on my part copying the defaults. 52e4629e9
